/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import materia.Materia;
import testMain.Colegio;

/**
 *
 * @author Emiliano
 */
public class AltaDeMaterias extends javax.swing.JInternalFrame {
    Colegio colegio;
    /**
     * Creates new form AltaDeMaterias
     */
    public AltaDeMaterias(Colegio colegio) {
        initComponents();
        this.colegio=colegio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLformularioDeMaterias = new javax.swing.JLabel();
        jLCodigoDeMateria = new javax.swing.JLabel();
        jLNombreDeLaMateria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTCodigoMateria = new javax.swing.JTextField();
        jTNombreMateria = new javax.swing.JTextField();
        jTAñoMateria = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        jLformularioDeMaterias.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLformularioDeMaterias.setText("Formulario de Materias");

        jLCodigoDeMateria.setText("CODIGO DE MATERIA:");

        jLNombreDeLaMateria.setText("NOMBRE DE LA MATERIA:");

        jLabel1.setText("AÑO AL QUE PERTENECE:");

        jTCodigoMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTCodigoMateriaKeyTyped(evt);
            }
        });

        jTNombreMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreMateriaKeyTyped(evt);
            }
        });

        jTAñoMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAñoMateriaActionPerformed(evt);
            }
        });
        jTAñoMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTAñoMateriaKeyTyped(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCodigoDeMateria)
                            .addComponent(jLNombreDeLaMateria)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNombreMateria)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTAñoMateria))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSalir))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jLformularioDeMaterias)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLformularioDeMaterias)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCodigoDeMateria)
                    .addComponent(jTCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombreDeLaMateria)
                    .addComponent(jTNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTAñoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo)
                    .addComponent(jBSalir)
                    .addComponent(jBGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        String nom = jTNombreMateria.getText();
        int id =Integer.parseInt(jTCodigoMateria.getText());
        int anio = Integer.parseInt(jTAñoMateria.getText());
        Materia m = new Materia(id,nom,anio);
        if(colegio.darAltaMateria(m)){
        JOptionPane.showMessageDialog(this,"Materia dada de alta exitosamente");
        }else{JOptionPane.showMessageDialog(this,"La materia ya esta dada de alta");}
        
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTCodigoMateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCodigoMateriaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(this,"Ingrese solo numeros");
        }
    }//GEN-LAST:event_jTCodigoMateriaKeyTyped

    private void jTNombreMateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreMateriaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isDigit(validar)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(this,"ingrese solo letras");
        }
    }//GEN-LAST:event_jTNombreMateriaKeyTyped

    private void jTAñoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAñoMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAñoMateriaActionPerformed

    private void jTAñoMateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTAñoMateriaKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(this,"ingrese solo el numero. Ejemplo(para 1er año ingrese 1)");
        }
    }//GEN-LAST:event_jTAñoMateriaKeyTyped

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        // TODO add your handling code here:
        jTCodigoMateria.setText("");
        jTNombreMateria.setText("");
        jTAñoMateria.setText("");
    }//GEN-LAST:event_jBNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLCodigoDeMateria;
    private javax.swing.JLabel jLNombreDeLaMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLformularioDeMaterias;
    private javax.swing.JTextField jTAñoMateria;
    private javax.swing.JTextField jTCodigoMateria;
    private javax.swing.JTextField jTNombreMateria;
    // End of variables declaration//GEN-END:variables
}
