/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;


import alumno.Alumno;
import materia.Materia;
import testMain.Colegio;

/**
 *
 * @author Emiliano
 */
public class MenuPrincipal extends javax.swing.JFrame {
    Colegio colegio = new Colegio();
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlta = new javax.swing.JMenu();
        jMAltaAlumnos = new javax.swing.JMenuItem();
        jMAltaMaterias = new javax.swing.JMenuItem();
        jMFormularios = new javax.swing.JMenu();
        jMFormularioInscripcion = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();
        jMSalir1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMAlta.setText("Alta");

        jMAltaAlumnos.setText("Alta de Alumnos");
        jMAltaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAltaAlumnosActionPerformed(evt);
            }
        });
        jMAlta.add(jMAltaAlumnos);

        jMAltaMaterias.setText("Alta de Materias");
        jMAltaMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAltaMateriasActionPerformed(evt);
            }
        });
        jMAlta.add(jMAltaMaterias);

        jMenuBar1.add(jMAlta);

        jMFormularios.setText("Formularios");

        jMFormularioInscripcion.setText("Formulario de inscripcion");
        jMFormularioInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFormularioInscripcionActionPerformed(evt);
            }
        });
        jMFormularios.add(jMFormularioInscripcion);

        jMenuBar1.add(jMFormularios);

        jMSalir.setText("Salir");

        jMSalir1.setText("Salir");
        jMSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalir1ActionPerformed(evt);
            }
        });
        jMSalir.add(jMSalir1);

        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMAltaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAltaAlumnosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AltaDeAlumnos alta = new AltaDeAlumnos(colegio);
        alta.setVisible(true);
        escritorio.add(alta);
        escritorio.moveToFront(alta);
    }//GEN-LAST:event_jMAltaAlumnosActionPerformed

    private void jMAltaMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAltaMateriasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AltaDeMaterias alta = new AltaDeMaterias(colegio);
        alta.setVisible(true);
        escritorio.add(alta);
        escritorio.moveToFront(alta);
    }//GEN-LAST:event_jMAltaMateriasActionPerformed

    private void jMSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalir1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMSalir1ActionPerformed

    private void jMFormularioInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFormularioInscripcionActionPerformed
        // TODO add your handling code here:
     colegio.darAltaMateria(new Materia(1,"Ingles",1));  
     colegio.darAltaMateria(new Materia(2,"Matematicas",1));
     colegio.darAltaMateria(new Materia(3,"Laboratorio",1));
     
     colegio.darAltaAlumno(new Alumno(1001,"Lopez","Martin"));
     colegio.darAltaAlumno(new Alumno(1002,"Martinez","Brenda"));
     
     
        
        escritorio.removeAll();
        escritorio.repaint();
        FormularioDeInscripcion form = new FormularioDeInscripcion(colegio.getSetAlum(),colegio.getSetMat());
        form.setVisible(true);
        escritorio.add(form);
        escritorio.moveToFront(form);    
    }//GEN-LAST:event_jMFormularioInscripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMAlta;
    private javax.swing.JMenuItem jMAltaAlumnos;
    private javax.swing.JMenuItem jMAltaMaterias;
    private javax.swing.JMenuItem jMFormularioInscripcion;
    private javax.swing.JMenu jMFormularios;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuItem jMSalir1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
